on:
  push:
  pull_request:
  workflow_call:
    inputs:
      ref:
        type: "string"
        required: true
        description: "The ref (branch or tag) to build"

jobs:
  build-frontend:
    name: "Build frontend"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          ref: "${{ inputs.ref }}"
      - uses: "actions/setup-node@v6"
        with:
          node-version: "lts/*"
          check-latest: true
          cache: "yarn"
      - run: "yarn install --frozen-lockfile --dev"
      - run: "yarn build"
      - uses: "actions/upload-artifact@v7"
        with:
          name: "frontend"
          path: "dist"
          retention-days: 5

  build-backend:
    name: "Build backend"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          ref: "${{ inputs.ref }}"
      - uses: "astral-sh/setup-uv@v8.1.0"
      - run: "export CADQUERY_WEB_VIEWER_SKIP_FRONTEND_BUILD=true && uv sync --frozen"
      - run: "export CADQUERY_WEB_VIEWER_SKIP_FRONTEND_BUILD=true && uv build"
      - uses: "actions/upload-artifact@v7"
        with:
          name: "wheel"
          path: "dist/*"
          retention-days: 5

  build-logo:
    name: "Build logo"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          ref: "${{ inputs.ref }}"
      - uses: "astral-sh/setup-uv@v8.1.0"
      - run: "export CADQUERY_WEB_VIEWER_SKIP_FRONTEND_BUILD=true && uv run --frozen python cadquery_web_viewer/logo.py"
      - uses: "actions/upload-artifact@v7"
        with:
          name: "logo"
          path: "assets/logo_build"
          retention-days: 5

  build-example:
    name: "Build examples (in-process)"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v6"
        with:
          ref: "${{ inputs.ref }}"
      - uses: "astral-sh/setup-uv@v8.1.0"
      - run: "export CADQUERY_WEB_VIEWER_SKIP_FRONTEND_BUILD=true && uv run --frozen python examples/in-process/object.py"
      - uses: "actions/upload-artifact@v7"
        with:
          name: "examples-in-process-export"
          path: "export"
          retention-days: 5
